name: RunBuild

on:
  workflow_call:
    inputs:
      push_true:
        required: true
        type: boolean
        default: true

jobs:
  build_module:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v5

      - name: Zip
        env:
          MODULEPATH: magisk-module
        run: |
          MODULEPROP=$MODULEPATH/module.prop
          MODULEID=$(grep id $MODULEPROP | cut -c4-)
          MODULEVER=$(grep -w version $MODULEPROP | cut -c9-)-$(grep versionCode $MODULEPROP | cut -c13-)
          cd $MODULEPATH
          zip -r ../"$MODULEID-$MODULEVER".zip .
          echo "set github env"
          echo "module_id=$MODULEID" >> $GITHUB_ENV
          echo "module_ver=$MODULEVER" >> $GITHUB_ENV

      - name: Actions
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.module_id}}-${{env.module_ver}}
          path: ./*.zip
