name: Build

on:
  workflow_call:
    inputs:
      push_true:
        required: true
        type: boolean
        default: true

jobs:
  build_module:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v5

      - name: Zip
        env:
          MODULEPATH: magisk-module
          MODULEPROP: ./$MODULEPATH/module.prop
          MODULEID: $(grep id $MODULEPROP | cut -c4-)
          MODULEVER: $(grep -w version $module_prop | cut -c9-)-$(grep versionCode $module_prop | cut -c13-)
        run: |
          cd $MODULEPATH
          zip -r ../$module_id-$module_ver.zip .

      - name: Actions
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.MODULEID}}-${{env.MODULEVER}}
          path: ./*.zip
